# Generated by Django 6.0 on 2026-01-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdb',
            old_name='contact',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='memberdb',
            name='email',
            field=models.CharField(default='unknown@gmail.com', max_length=64),
            preserve_default=False,
        ),
    ]
