# Generated by Django 6.0 on 2026-01-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_contact_memberdb_phone_memberdb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticesDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('PUB', 'public'), ('PRI', 'private')], default='PRI', max_length=3)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
