# Generated by Django 6.0 on 2026-01-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_noticesdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatData',
            fields=[
                ('flat_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='memberdb',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='memberdb',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='memberdb',
            name='flat_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.flatdata'),
        ),
    ]
