# Generated by Django 6.0 on 2026-01-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_flatdata_alter_memberdb_age_alter_memberdb_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=64)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
