# Generated by Django 6.0.1 on 2026-01-10 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='member',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='api.memberdb'),
            preserve_default=False,
        ),
    ]
